# ./docker-compose.yml

version: '3'

services:
  db:
    build: ./BD
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: COLUNCOL
      MYSQL_USER: coluncol
      MYSQL_PASSWORD: coluncolpass
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8101:80"
    stdin_open: true
    tty: true